modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="creategear"
version="1.0"
displayName="Create Gear"
authors="Destined"
description='''
Adds a few new tools utulizing Create!
'''
[[dependencies.creategear]] #optional
   modId="forge"
   mandatory=true
   versionRange="[43,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.creategear]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
